# Generated by Django 5.1.11 on 2025-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30, verbose_name="タイトル")),
                ("content", models.TextField(blank=True, max_length=100, null=True, verbose_name="コンテンツ")),
                ("created", models.DateTimeField(auto_now=True, verbose_name="作成日時")),
                ("updated", models.DateTimeField(auto_now_add=True, verbose_name="更新日時")),
            ],
        ),
    ]
