# Generated by Django 5.1.11 on 2025-09-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_tweet_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=50, verbose_name="コンテンツ"),
        ),
    ]
